version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MIX_ENV=dev
    volumes:
      - ./server:/app

  analytics:
    build: ./ds
    volumes:
      - ./ds/logs:/app/logs